[window]
opacity = 1.0

[colors.primary]
background = "0x002800"
foreground = "0x00FF00"

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 10

[font.normal]
family = "PxPlus IBM VGA 8x16"
style = "Regular"

[window.padding]
x = 0
y = 0
